name: Deploy Application

on:
  # Triggers the workflow only on tags creation
  create:
    ref_type: tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install the dependencies
        run: yarn

      - name: Build the application
        run: yarn build
      
      - name: Upload the build artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: build/

  gh-pages:
    needs: build

    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v2